#!/bin/bash
# /usr/local/bin/apply_network.sh

# 1. Move the YAML file generated by PHP into the system directory
mv /tmp/99-custom.yaml /etc/netplan/99-custom.yaml

# 2. Lock down permissions (Netplan requires this)
chmod 600 /etc/netplan/99-custom.yaml
chown root:root /etc/netplan/99-custom.yaml

# 3. Apply the changes
# This is the moment the IP drops and changes to static!
netplan apply